@server = http://localhost:3000

### 게시글 조회
GET {{server}}/blog

### 게시글 작성
POST {{server}}/blog
Content-Type: application/json

{
  "title": "안녕하세요",
  "content": "처음 인사드립니다.",
  "name": "손병환"
}

### 특정 게시물 조회
GET {{server}}/blog/6613bc4bcc4fb7df9051217b

### 게시물 삭제
DELETE {{server}}/blog/6613bb50379ef51839394c45

### 게시글 수정
PUT {{server}}/blog/6613bcc0634a38f422706a4b
Content-Type: application/json

{
  "title": "타이틀 수정3",
  "content": "본문 수정 3",
  "name": "손병환"
}
